# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Genomics Life
tagline:             'Ramblings about Genomics and all related science!'
description:         'Let there be science.'
url:                 http://genomicslife.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nitesh Turaga
  url:               https://twitter.com/niteshturaga
  email:             genomicslife@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
